### ISSUE TITLE
turn off gitbook's "discussions" feature

### ISSUE THREAD

**Issue by akbr** [TeamUpturn/predictivepolicing.info#1]
In settings: ![image](https://cloud.githubusercontent.com/assets/804208/15589919/f1a6e366-2362-11e6-8364-47abf65aaad4.png)

This will fix the popup error message currently showing at https://teamupturn.gitbooks.io/predictive-policing/content/

(You might not see the fix work until the next push.)

**Comment by dgrobinson** [comment]
Done.
